Repository vuejs-fr/vuejs.org, pull requests merged in 2018-04, with the labels that each got.

#126 Typo 'récurant' -> 'récurrent'
  themes/vue/layout/sponsors-page.ejs
Labels: Màj

#128 Traduction de `components-custom-events`
  src/v2/guide/components-custom-events.md
Labels: Validé

#129 Traduction de `components-dynamic-async`
  src/v2/guide/components-dynamic-async.md
Labels: Relecture nécessaire

#130 Traduction de `component-edge-cases`
  src/v2/guide/components-edge-cases.md
Labels: Relecture nécessaire
