Repository vuejs-fr/vuejs.org, pull requests merged in 2018-06, with the labels that each got.

#127 Retraduction de `components.md`
  src/v2/guide/components.md
Labels: Màj, Relecture nécessaire

#124 Traduction de `unit-testing-vue-components.md`
  src/v2/cookbook/unit-testing-vue-components.md
Labels: Relecture nécessaire

#121 Traduction de `editable-svg-icons.md`
  src/v2/cookbook/editable-svg-icons.md
Labels: Relecture nécessaire

#137 [Mise à jour] — Juin 2018
  src/images/devtools-storage-chrome.png
  src/images/devtools-storage-edge.png
  src/images/devtools-storage.png
  src/v2/api/index.md
  src/v2/cookbook/avoiding-memory-leaks.md
  src/v2/cookbook/client-side-storage.md
  src/v2/cookbook/creating-custom-scroll-directives.md
  src/v2/cookbook/packaging-sfc-for-npm.md
  src/v2/cookbook/unit-testing-vue-components.md
  src/v2/guide/comparison.md
  src/v2/guide/components-custom-events.md
  src/v2/guide/components-props.md
  src/v2/guide/components.md
  src/v2/guide/deployment.md
  src/v2/guide/events.md
  src/v2/guide/forms.md
  src/v2/guide/installation.md
  src/v2/guide/join.md
  src/v2/guide/list.md
  src/v2/guide/single-file-components.md
  src/v2/guide/transitions.md
  src/v2/guide/typescript.md
  src/v2/guide/unit-testing.md
  src/v2/style-guide/index.md
  themes/vue/_config.yml
  themes/vue/layout/layout.ejs
  themes/vue/layout/partials/ad.ejs
  themes/vue/layout/sponsors-page.ejs
  themes/vue/source/css/_sponsors-page.styl
  themes/vue/source/images/dopamine.png
  themes/vue/source/js/vue.js
  themes/vue/source/js/vue.min.js
Labels: Màj, Relecture nécessaire

#140 Correction mineure grammaire
  src/v2/guide/components.md
Labels: Màj, Relecture nécessaire, Validé

#142 Correction fixer -> corriger + mise à jour nom rubrique composants
  src/v2/guide/components.md
Labels: Màj, Relecture nécessaire, Validé

#143 Update custom-directive.md
  src/v2/guide/custom-directive.md
Labels: Màj, Relecture nécessaire, Validé

#144 Update custom-directive.md
  src/v2/guide/custom-directive.md
Labels: Màj, Relecture nécessaire, Validé

#146 June 2018
  src/v2/api/index.md
  src/v2/cookbook/avoiding-memory-leaks.md
  src/v2/cookbook/client-side-storage.md
  src/v2/cookbook/debugging-in-vscode.md
  src/v2/cookbook/dockerize-vuejs-app.md
  src/v2/cookbook/form-validation.md
  src/v2/cookbook/unit-testing-vue-components.md
  src/v2/guide/comparison.md
  src/v2/guide/components.md
  src/v2/guide/events.md
  src/v2/guide/index.md
  src/v2/guide/installation.md
  src/v2/guide/join.md
  src/v2/guide/migration.md
  src/v2/guide/transitions.md
  src/v2/guide/unit-testing.md
  themes/vue/_config.yml
  themes/vue/layout/partials/ecosystem_dropdown.ejs
  themes/vue/source/css/_scrimba.styl
  themes/vue/source/css/page.styl
  themes/vue/source/images/vuemastery.png
Labels: Màj, Relecture nécessaire
